POST http://127.0.0.1:8000/api/auth/token/login/ HTTP/1.1
content-type: application/json

{
    "username": "yuri",
    "email": "yuri@ya.ru",
    "first_name": "yuri",
    "last_name": "gagarin",
    "password": "yuri100500"

}