# Generated by Django 3.2.8 on 2021-10-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211021_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
